# -*- makefile -*-
# $Id: Makefile,v 1.7 1997/06/19 19:09:58 pmartin Exp $

DFS_FLAGS = -DNO_ERROR_HANDLING -DSTATS -DCONCISE
CXXFLAGS += $(DFS_FLAGS)

BINARIES = bim_dfs

MAIN = dfs_run.cc

PKGTYPE = cc

# pick options for the binaries
bim_dfs_opts= -DBDFS

include ../../make.config

