#!/bin/sh
ulimit -t 1800

binary=$1 
if [ $1 = bim_ld ]
then
	opt=2
fi

${bindir}$binary $opt < $2 >> ${resultsdir}$1.$3

# if program is aborted (e.g. because of cpu time limit) we return 1

if [ $? != 0 ]
then
   exit 1
fi
