#!/bin/sh
bindir=${bindir-../bin/}; export bindir

resultsdir=${resultsdir-../results/}; export resultsdir

prognames=${prognames-"bim_fifo bim_lo bim_hi bim_ar bim_dfs bim_bfs bim_ld"}; export prognames

numvertices=${numvertices-"100"}; export numvertices

cutnumseeds=${cutnumseeds-1}; export cutnumseeds


seedlist=${seedlist-`awk "BEGIN {s=25; for(i=0; i<${cutnumseeds};i++) {s+=10; print s}}"`}; export seedlist


tempfile=/tmp/unibm`date +%s`
typelist=$@
avdegree=6

for type in $typelist 
do
  for prog in $prognames
  do
    rm -f ${resultsdir}$prog.$type
    echo "$prog.$type" >> ${resultsdir}$prog.$type
    echo "   Nodes     Arcs     Size  Op. Cnt.        Time"  >> ${resultsdir}$prog.$type  
  done

  gs=1
  for n in $numvertices
  do
    sd=1  	
    m=`expr $n "*" $avdegree`
      for prog in $prognames
      do
          echo "-1 $n $m" >> ${resultsdir}$prog.$type
      done
    for seed in $seedlist
    do
      echo "c Generator setting:  $gs       Seed #:  $sd"
      rm -f $tempfile
      echo "${bindir}unibm -NU $n -NV $n -NE $m -seed $seed -kind $type | sort -r > $tempfile"
      ${bindir}unibm -NU $n -NV $n -NE $m -seed $seed -kind $type | sort -r > $tempfile
      for prog in $prognames
      do
          ex-prog $prog $tempfile $type
      done
      rm -f $tempfile
      sd=`expr $sd + 1`
    done
    gs=`expr $gs + 1`
  done
done


