CFLAGS= -O
COMP=gcc

io.o : io.c
	$(COMP) -c $(CFLAGS) io.c

manip.o : manip.c
	$(COMP) -c $(CFLAGS) manip.c

utility.o : utility.c
	$(COMP) -c $(CFLAGS) utility.c

timer.o : timer.c
	$(COMP) -c $(CFLAGS) timer.c

all: io.o manip.o utility.o timer.o

